services:
  app:
    container_name: signal_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:3000'

  signal:
    container_name: signal_api
    image: bbernhard/signal-cli-rest-api:0.66
    ports:
      - '8080:8080'
    environment:
      - MODE=${MODE:-json-rpc}
    volumes:
      - ./signal:/home/.local/share/signal-cli:Z
